# Generated by Django 5.2.6 on 2026-02-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
